apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  #namespace: roboshop
spec:
  type: "{{ .Values.service.type}}"
#labels are used as selectors to select the pods to which this service will route the traffic
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80  #service port
      targetPort: 80